---
  - hosts: localhost
    connection: local
    gather_facts: false
    tasks:
      - name: Get a JWT token to authenticate API requests
        uri:
          url: "{{ CSAPIURL }}/oauth2/token"
          method: POST
          headers:
            accept: application/json
          body_format: form-urlencoded
          body:
            client_id: "{{ lookup('env','CSCLIENTID') }}"
            client_secret: "{{ lookup('env','CSCLIENTSECRET') }}"
          status_code: 201
        register: response
      - name: Print the JWT token
        ansible.builtin.debug:
          msg: "{{ response.json.access_token }}"